### ISSUE TITLE
Installation Script Issue: Activating Pipenv in subshell

### ISSUE THREAD

**Issue by xchrisbradley** [massplanner/agent#1]
```bash
xchrisbradley@earth test % curl -fsSL https://raw.githubusercontent.com/massplanner/agent/main/install_script.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  779k    0  779k    0     0   846k      0 --:--:-- --:--:-- --:--:-- 5805k
Archive:  massplanner-agent.zip
5353aacb83ede75d3850613d585280cd39784242
   creating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.RqxOT0ht/massplanner-agent-5353aac/
  inflating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.RqxOT0ht/massplanner-agent-5353aac/.env.example  
  inflating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.RqxOT0ht/massplanner-agent-5353aac/.gitignore  
  inflating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.RqxOT0ht/massplanner-agent-5353aac/Pipfile  
  inflating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.RqxOT0ht/massplanner-agent-5353aac/Pipfile.lock  
  inflating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.RqxOT0ht/massplanner-agent-5353aac/README.md  
   creating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.RqxOT0ht/massplanner-agent-5353aac/__data__/
  inflating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.RqxOT0ht/massplanner-agent-5353aac/__data__/frankenstein.html  
  inflating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.RqxOT0ht/massplanner-agent-5353aac/__data__/jack-sparrow-resume.pdf  
  inflating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.RqxOT0ht/massplanner-agent-5353aac/__data__/sample-resume.pdf  
  inflating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.RqxOT0ht/massplanner-agent-5353aac/__data__/standard-occupations.json  
  inflating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.RqxOT0ht/massplanner-agent-5353aac/__data__/zeroshot-resume-features.json  
  inflating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.RqxOT0ht/massplanner-agent-5353aac/install_script.sh  
 extracting: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.RqxOT0ht/massplanner-agent-5353aac/massplanner.py  
   creating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.RqxOT0ht/massplanner-agent-5353aac/massplanner/
 extracting: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.RqxOT0ht/massplanner-agent-5353aac/massplanner/__init__.py  
   creating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.RqxOT0ht/massplanner-agent-5353aac/massplanner/common/
 extracting: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.RqxOT0ht/massplanner-agent-5353aac/massplanner/common/__init__.py  
Requirement already satisfied: pipenv in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (2023.9.1)
Requirement already satisfied: certifi in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from pipenv) (2023.7.22)
Requirement already satisfied: virtualenv>=20.24.2 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from pipenv) (20.24.4)
Requirement already satisfied: setuptools>=67.0.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from pipenv) (68.1.2)
Requirement already satisfied: distlib<1,>=0.3.7 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from virtualenv>=20.24.2->pipenv) (0.3.7)
Requirement already satisfied: filelock<4,>=3.12.2 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from virtualenv>=20.24.2->pipenv) (3.12.3)
Requirement already satisfied: platformdirs<4,>=3.9.1 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from virtualenv>=20.24.2->pipenv) (3.10.0)
Requirement already satisfied: typing-extensions>=4.7.1; python_version < "3.11" in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from filelock<4,>=3.12.2->virtualenv>=20.24.2->pipenv) (4.7.1)
WARNING: You are using pip version 20.2.3; however, version 23.2.1 is available.
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 -m pip install --upgrade pip' command.
Creating a virtualenv for this project...
Pipfile: /Users/xchrisbradley/Desktop/test/massplanner-agent/Pipfile
Using /usr/bin/python3 (3.9.6) to create virtualenv...
⠸ Creating virtual environment...created virtual environment CPython3.9.6.final.0-64 in 191ms
  creator CPython3macOsFramework(dest=/Users/xchrisbradley/.local/share/virtualenvs/massplanner-agent-bUtNUmIs, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/xchrisbradley/Library/Application Support/virtualenv)
    added seed packages: pip==23.2.1, setuptools==68.1.2, wheel==0.41.2
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment!
Virtualenv location: /Users/xchrisbradley/.local/share/virtualenvs/massplanner-agent-bUtNUmIs
Installing dependencies from Pipfile.lock (c9f37e)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Installing dependencies from Pipfile.lock (c9f37e)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
All dependencies are now up-to-date!
Launching subshell in virtual environment...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pipenv/__main__.py", line 4, in <module>
    cli()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pipenv/cli/options.py", line 58, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pipenv/cli/command.py", line 396, in shell
    do_shell(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pipenv/routines/shell.py", line 46, in do_shell
    shell.fork_compat(*fork_args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pipenv/shells.py", line 124, in fork_compat
    c.interact(escape_character=None)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pipenv/vendor/pexpect/pty_spawn.py", line 788, in interact
    mode = tty.tcgetattr(self.STDIN_FILENO)
termios.error: (25, 'Inappropriate ioctl for device')
Installation complete. You can now run your program using 'python massplanner.py --resume /path/to/resume/location'
bash: line 50: deactivate: command not found
xchrisbradley@earth test % 
```

**Comment by xchrisbradley** [comment]
Fixed with this [Commit](https://github.com/massplanner/agent/commit/dc97db52aacf6947bf351a74ff2b12d485c393c2) 

```bash
xchrisbradley@earth test % curl -fsSL https://raw.githubusercontent.com/massplanner/agent/main/install_script.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1558k    0 1558k    0     0  1586k      0 --:--:-- --:--:-- --:--:-- 6627k
Archive:  massplanner-agent.zip
dc97db52aacf6947bf351a74ff2b12d485c393c2
   creating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.6HzuBdOQ/massplanner-agent-dc97db5/
  inflating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.6HzuBdOQ/massplanner-agent-dc97db5/.env.example  
  inflating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.6HzuBdOQ/massplanner-agent-dc97db5/.gitignore  
  inflating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.6HzuBdOQ/massplanner-agent-dc97db5/Pipfile  
  inflating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.6HzuBdOQ/massplanner-agent-dc97db5/Pipfile.lock  
  inflating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.6HzuBdOQ/massplanner-agent-dc97db5/README.md  
   creating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.6HzuBdOQ/massplanner-agent-dc97db5/__data__/
  inflating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.6HzuBdOQ/massplanner-agent-dc97db5/__data__/frankenstein.html  
  inflating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.6HzuBdOQ/massplanner-agent-dc97db5/__data__/jack-sparrow-resume.pdf  
  inflating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.6HzuBdOQ/massplanner-agent-dc97db5/__data__/sample-resume.pdf  
  inflating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.6HzuBdOQ/massplanner-agent-dc97db5/__data__/standard-occupations.json  
  inflating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.6HzuBdOQ/massplanner-agent-dc97db5/__data__/zeroshot-resume-features.json  
  inflating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.6HzuBdOQ/massplanner-agent-dc97db5/install_script.sh  
   creating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.6HzuBdOQ/massplanner-agent-dc97db5/massplanner-agent/
  inflating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.6HzuBdOQ/massplanner-agent-dc97db5/massplanner-agent/Pipfile  
  inflating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.6HzuBdOQ/massplanner-agent-dc97db5/massplanner-agent/Pipfile.lock  
  inflating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.6HzuBdOQ/massplanner-agent-dc97db5/massplanner-agent/README.md  
   creating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.6HzuBdOQ/massplanner-agent-dc97db5/massplanner-agent/__data__/
  inflating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.6HzuBdOQ/massplanner-agent-dc97db5/massplanner-agent/__data__/frankenstein.html  
  inflating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.6HzuBdOQ/massplanner-agent-dc97db5/massplanner-agent/__data__/jack-sparrow-resume.pdf  
  inflating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.6HzuBdOQ/massplanner-agent-dc97db5/massplanner-agent/__data__/sample-resume.pdf  
  inflating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.6HzuBdOQ/massplanner-agent-dc97db5/massplanner-agent/__data__/standard-occupations.json  
  inflating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.6HzuBdOQ/massplanner-agent-dc97db5/massplanner-agent/__data__/zeroshot-resume-features.json  
  inflating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.6HzuBdOQ/massplanner-agent-dc97db5/massplanner-agent/install_script.sh  
 extracting: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.6HzuBdOQ/massplanner-agent-dc97db5/massplanner-agent/massplanner.py  
   creating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.6HzuBdOQ/massplanner-agent-dc97db5/massplanner-agent/massplanner/
 extracting: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.6HzuBdOQ/massplanner-agent-dc97db5/massplanner-agent/massplanner/__init__.py  
   creating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.6HzuBdOQ/massplanner-agent-dc97db5/massplanner-agent/massplanner/common/
 extracting: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.6HzuBdOQ/massplanner-agent-dc97db5/massplanner-agent/massplanner/common/__init__.py  
 extracting: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.6HzuBdOQ/massplanner-agent-dc97db5/massplanner.py  
   creating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.6HzuBdOQ/massplanner-agent-dc97db5/massplanner/
 extracting: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.6HzuBdOQ/massplanner-agent-dc97db5/massplanner/__init__.py  
   creating: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.6HzuBdOQ/massplanner-agent-dc97db5/massplanner/common/
 extracting: /var/folders/bx/bk53vj7j46v9vrmx231v8v_r0000gn/T/tmp.6HzuBdOQ/massplanner-agent-dc97db5/massplanner/common/__init__.py  
Requirement already satisfied: pipenv in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (2023.9.1)
Requirement already satisfied: certifi in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from pipenv) (2023.7.22)
Requirement already satisfied: virtualenv>=20.24.2 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from pipenv) (20.24.4)
Requirement already satisfied: setuptools>=67.0.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from pipenv) (68.1.2)
Requirement already satisfied: platformdirs<4,>=3.9.1 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from virtualenv>=20.24.2->pipenv) (3.10.0)
Requirement already satisfied: filelock<4,>=3.12.2 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from virtualenv>=20.24.2->pipenv) (3.12.3)
Requirement already satisfied: distlib<1,>=0.3.7 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from virtualenv>=20.24.2->pipenv) (0.3.7)
Requirement already satisfied: typing-extensions>=4.7.1; python_version < "3.11" in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from filelock<4,>=3.12.2->virtualenv>=20.24.2->pipenv) (4.7.1)
WARNING: You are using pip version 20.2.3; however, version 23.2.1 is available.
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 -m pip install --upgrade pip' command.
Skipping virtualenv activation
Installation complete. You can now run your program using 'python massplanner-agent/massplanner.py --resume /path/to/resume/location'
xchrisbradley@earth test % ls
```
